name: 功能优化建议
description: 选这个，帮助2kbit变得更完美！
title: '[建议]: '
labels: [ "质量更新" ]
assignees: [ "Abjust" ]

body:
  - type: markdown
    attributes:
      value: |
        ### （模板来源：[HanBot](https://github.com/daizihan233/HanBot)）
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确定您做到了以下内容
      options:
        - label: "我确定这是个有意义的Issue。"
          required: true
  - type: input
    id: name
    attributes:
      label: 要优化的功能名称
      description: |
        如果希望（或者知道怎样让）机器人运行更高效，请写“机器人”
  - type: textarea
    id: description
    attributes:
      label: 应该如何优化？
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: 为什么提出这个建议？