name: Compile 2kbit-intp

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        
      - name: Install dependencies
        run: pdm install
        
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          include-plugin-directory: codeintp
          standalone: true
          onefile: true

      - id: string
        name: Lowercase String
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ runner.os }}

      - id: commit
        name: Get Commit Hash
        uses: prompt/actions-commit-hash@v3
        with:
          push: true
          tags: ${{ steps.commit.outputs.short }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 2kbit-intp-${{ steps.commit.outputs.short }}-${{ steps.string.outputs.lowercase }}
          path: |
            build/*.exe
            build/*
